name: Update gh-pages Branch

on:
  push:
    tags:
      - v*

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # Determine where the gh-pages branch will be checked out
      - name: Set $GH_PAGES
        run: echo GH_PAGES=${GITHUB_WORKSPACE}/.gh-pages >> $GITHUB_ENV
      # Check out the master branch
      - uses: actions/checkout@v2
      # Check out the gh-pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ${{ env.GH_PAGES }}
      # Compile main.js and copy it to the gh-pages checkout
      - name: Compile JS
        run: |
          npm install
          npm run compile
          cp index.html main.js ${GH_PAGES}
      # Commit & push to gh-pages on GitHub
      - name: Push gh-pages
        run: ${GITHUB_WORKSPACE}/scripts/push-to-gh-pages.sh
        working-directory: ${{ env.GH_PAGES }}
